# Generated by Django 6.0.6 on 2026-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imageName',
            field=models.CharField(default='first-post.jpg', max_length=100),
        ),
    ]
