# Generated by Django 6.0.6 on 2026-06-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt_post_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imageName',
            new_name='image_name',
        ),
    ]
